### ISSUE TITLE
IF does not work as expected

### ISSUE THREAD

**Issue by afurey0** [handsontable/ruleJS#13]
When a parameter of an IF call has division by zero, the entire cell errors out even if that parameter should not ever be evaluated.

For example, take the cell contents: '=IF(1=0,1/0,0)'. It always errors out even though there is logically no way to get to '1/0'. In Excel this function will work as expected, as it only evaluates the arguments as needed (working more like an inline-if than an if-function).

**Comment by mahidaparth7** [comment]
Is there any workaround for this issue?

**Comment by AMBudnik** [comment]
Thank you for sharing @Tsumikiri 

I have replicated the issue with this demo: http://jsfiddle.net/handsoncode/kunx7g5v/
(testing v.1.10.0)

You are right in this example

`=IF(1 = 0, 1/0, 0)`

we get `#DIV/0!` even if the loaded value should be `0` not `1/0`

**Comment by jnbarchan** [comment]
`IF` always evaluates all its arguments.  So to workaround and prevent the "division by zero" you could do anything like:

    A1 = 20, A2 = 0
    =IF( A2 = 0, 0, A1 / IF( A2 = 0, 1, A2) )

This means that if `A2 = 0` --- we know the outer `IF` will be returning 0 as the result anyway --- the inner `IF` is just there to prevent the "unused" side of the expression actually dividing by 0, it divides by 1 instead, and then its result gets ignored!

**Comment by Tsumikiri** [comment]
Thanks for the workaround, @jnbarchan 
It's a good alternative until a true fix is created.
