### ISSUE TITLE
Paste and autofill formula [improvement]

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/ruleJS#6]
@dnprock said:

`Current paste functionality only put in the exact value of copy. If I copy "=A2+B2" in C2 and paste to C3, the formula is still "=A2+B2". It should be autofill in this case and increment to "=A3+B3". This is how Google spreadsheet works.`

**Comment by gavargas22** [comment]
Hey guys, was this enhancement implemented? I did not find it on the documentation

**Comment by AMBudnik** [comment]
To be honest we decided not to evaluate the RuleJS. Now the formula-parser is the project to follow as it runs the Formula plugin in the Handsontable PRO.

**Comment by gavargas22** [comment]
Thanks for the info as alway @AMBudnik

**Comment by AMBudnik** [comment]
you're welcome @gavargas22 :)
