### ISSUE TITLE
COUNTIF doesn't work. & AVERAGEIF doesn't work special case.

### ISSUE THREAD

**Issue by belldoor** [handsontable/ruleJS#9]
If I use COUNTIF function in demo page, it doesn't work. (also, in my project)
example, I use this formula 
=COUNTIF(A1:A5, ">0")
unfortunately, it returns #ERROR

and another issue in AVERAGEIF function.
when I use AVERAGEIF function, and define criteria only 'number' it works.
but, when I define criteria with some formula (like =A1 \* B1 ~ =A5 \* B5)
it also returns #ERROR.

how can I fixed it? this project no one no longer maintained?

**Comment by bryanbraun** [comment]
I came across the AVERAGEIF issue as well. I noticed a few issues:
1. The code basically assumes the cells are numeric for both the range and criteria.
2. The criteria parameter requires an operator... there is no implied equals

These issues occur whether or not the third optional parameter is used.
For example:

 | A | B 
 --- | --- | ---
1 | 1 | 1
2 | -1 | 2
3 | yes | 3
4 | no | 4

Works? | Formula 
 ------------ | -------------
:white_check_mark: | `=AVERAGEIF(A1:A2, '>0')`
:x: | `=AVERAGEIF(A1:A2, '1')`
:x: | `=AVERAGEIF(A3:A4, 'yes')`

One other minor issue is that this AVERAGEIF accepts non-range values, whereas the ones used in excel and google sheets do not.
